name: Generate Documentation

on:
  push:
    tags:
      - '*'

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Run Doxygen
        run: doxygen Doxyfile 

      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: html/